# databases
brew "redis"

# development tools
brew "git"

# development tools - go
brew "go"
brew "glide"

# development tools - javascript
brew "nodejs"

# development tools -ruby
brew "rbenv"

# utilities
brew "wget"

